version: '3.4'

services:
  socketioparser:
    image: socketioparser
    build:
      context: server/node_modules/socket.io-parser
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
